<a href="https://colab.research.google.com/github/tleitch/Course_AWS_Certified_Machine_Learning/blob/master/Untitled4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install pyreadstat

Collecting pyreadstat
  Downloading pyreadstat-1.1.3-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.4 MB)
     |████████████████████████████████| 2.4 MB 30.4 MB/s
Requirement already satisfied: pandas>0.24.0 in /usr/local/lib/python3.7/dist-packages (from pyreadstat) (1.1.5)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>0.24.0->pyreadstat) (2018.9)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas>0.24.0->pyreadstat) (1.19.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>0.24.0->pyreadstat) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>0.24.0->pyreadstat) (1.15.0)
Installing collected packages: pyreadstat
Successfully installed pyreadstat-1.1.3

In [74]:
import pandas
import pyreadstat
df, meta = pyreadstat.read_sas7bdat('all_data_2021apr.sas7bdat')

In [5]:
df.head()

  PROVIDER_ID  HAI_1_DEN_VOL  HAI_2_DEN_VOL  ...  OP_35_ED_DEN  OP_36  OP_36_DEN
0      010001         7846.0        13268.0  ...         190.0    0.8      993.0
1      010005         3088.0         7928.0  ...         121.0    1.1      483.0
2      010006         5874.0        10270.0  ...           NaN    1.1      454.0
3      010007            NaN            NaN  ...           NaN    1.0       76.0
4      010008            NaN            NaN  ...           NaN    NaN        NaN

[5 rows x 99 columns]

In [58]:
ixMezAll=['PROVIDER_ID', 'HAI_1_DEN_VOL', 'HAI_2_DEN_VOL', 'HAI_3_DEN_VOL',
       'HAI_4_DEN_VOL', 'HAI_5_DEN_VOL', 'HAI_6_DEN_VOL', 'HAI_1_DEN_PRED',
       'HAI_2_DEN_PRED', 'HAI_3_DEN_PRED', 'HAI_4_DEN_PRED', 'HAI_5_DEN_PRED',
       'HAI_6_DEN_PRED', 'HAI_1', 'HAI_2', 'HAI_3', 'HAI_4', 'HAI_5', 'HAI_6',
       'READM_30_HOSP_WIDE', 'READM_30_HIP_KNEE', 'EDAC_30_HF',
       'READM_30_COPD', 'EDAC_30_AMI', 'EDAC_30_PN', 'MORT_30_STK',
       'MORT_30_PN', 'MORT_30_HF', 'MORT_30_COPD', 'MORT_30_AMI',
       'COMP_HIP_KNEE', 'READM_30_HOSP_WIDE_DEN', 'READM_30_HIP_KNEE_DEN',
       'EDAC_30_HF_DEN', 'READM_30_COPD_DEN', 'EDAC_30_AMI_DEN',
       'EDAC_30_PN_DEN', 'MORT_30_STK_DEN', 'MORT_30_PN_DEN', 'MORT_30_HF_DEN',
       'MORT_30_COPD_DEN', 'MORT_30_AMI_DEN', 'COMP_HIP_KNEE_DEN', 'OP_2',
       'OP_2_DEN', 'OP_3B', 'OP_3B_DEN', 'OP_8', 'OP_8_DEN', 'OP_10',
       'OP_10_DEN', 'OP_13', 'OP_13_DEN', 'OP_18B', 'OP_18B_DEN', 'OP_22',
       'OP_22_DEN', 'OP_23', 'OP_23_DEN', 'OP_29', 'OP_29_DEN', 'OP_30',
       'OP_30_DEN', 'PSI_4_SURG_COMP', 'PSI_4_SURG_COMP_DEN', 'PSI_90_SAFETY',
       'IMM_3_DEN', 'IMM_3', 'PC_01', 'PC_01_DEN', 'SEP_1', 'SEP_1_DEN',
       'ED_2B', 'ED_2B_DEN', 'H_RESP_RATE_P', 'H_COMP_1_STAR_RATING',
       'H_COMP_2_STAR_RATING', 'H_COMP_3_STAR_RATING', 'H_COMP_5_STAR_RATING',
       'H_COMP_6_STAR_RATING', 'H_COMP_7_STAR_RATING', 'H_GLOB_STAR_RATING',
       'H_INDI_STAR_RATING', 'H_NUMB_COMP', 'PSI_90_SAFETY_DEN',
       'MORT_30_CABG', 'MORT_30_CABG_DEN', 'READM_30_CABG',
       'READM_30_CABG_DEN', 'OP_32', 'OP_32_DEN', 'OP_33', 'OP_33_DEN',
       'OP_35_ADM', 'OP_35_ADM_DEN', 'OP_35_ED', 'OP_35_ED_DEN', 'OP_36',
       'OP_36_DEN']


ix3='MORT_30_AMI MORT_30_CABG	MORT_30_COPD MORT_30_HF	MORT_30_PN	MORT_30_STK	PSI_4_SURG_COMP	COMP_HIP_KNEE HAI_1-HAI_6 PSI_90_SAFETY	EDAC_30_AMI EDAC_30_HF EDAC_30_PN OP_32 READM_30_CABG READM_30_COPD READM_30_HIP_KNEE READM_30_HOSP_WIDE OP_35_ADM OP_35_ED OP_36	H_COMP_1_STAR_RATING H_COMP_2_STAR_RATING H_COMP_3_STAR_RATING H_COMP_5_STAR_RATING H_COMP_6_STAR_RATING H_COMP_7_STAR_RATING H_GLOB_STAR_RATING H_INDI_STAR_RATING  IMM_3 OP_22	OP_23 OP_29 OP_30 OP_33 PC_01 SEP_1	OP_3b OP_18b ED_2b OP_8 OP_10 OP_13 OP_2'
ixUse=ix3.split()

In [9]:
print(ixUse)

['PROVIDER_ID', 'HAI_1_DEN_VOL', 'HAI_2_DEN_VOL', 'HAI_3_DEN_VOL', 'HAI_4_DEN_VOL', 'HAI_5_DEN_VOL', 'HAI_6_DEN_VOL', 'HAI_1_DEN_PRED', 'HAI_2_DEN_PRED', 'HAI_3_DEN_PRED', 'HAI_4_DEN_PRED', 'HAI_5_DEN_PRED', 'HAI_6_DEN_PRED', 'HAI_1', 'HAI_2', 'HAI_3', 'HAI_4', 'HAI_5', 'HAI_6', 'READM_30_HOSP_WIDE', 'READM_30_HIP_KNEE', 'EDAC_30_HF', 'READM_30_COPD', 'EDAC_30_AMI', 'EDAC_30_PN', 'MORT_30_STK', 'MORT_30_PN', 'MORT_30_HF', 'MORT_30_COPD', 'MORT_30_AMI', 'COMP_HIP_KNEE', 'READM_30_HOSP_WIDE_DEN', 'READM_30_HIP_KNEE_DEN', 'EDAC_30_HF_DEN', 'READM_30_COPD_DEN', 'EDAC_30_AMI_DEN', 'EDAC_30_PN_DEN', 'MORT_30_STK_DEN', 'MORT_30_PN_DEN', 'MORT_30_HF_DEN', 'MORT_30_COPD_DEN', 'MORT_30_AMI_DEN', 'COMP_HIP_KNEE_DEN', 'OP_2', 'OP_2_DEN', 'OP_3B', 'OP_3B_DEN', 'OP_8', 'OP_8_DEN', 'OP_10', 'OP_10_DEN', 'OP_13', 'OP_13_DEN', 'OP_18B', 'OP_18B_DEN', 'OP_22', 'OP_22_DEN', 'OP_23', 'OP_23_DEN', 'OP_29', 'OP_29_DEN', 'OP_30', 'OP_30_DEN', 'PSI_4_SURG_COMP', 'PSI_4_SURG_COMP_DEN', 'PSI_90_SAFETY', 'IMM_3_DEN', 'IMM_3', 'PC_01', 'PC_01_DEN', 'SEP_1', 'SEP_1_DEN', 'ED_2B', 'ED_2B_DEN', 'H_RESP_RATE_P', 'H_COMP_1_STAR_RATING', 'H_COMP_2_STAR_RATING', 'H_COMP_3_STAR_RATING', 'H_COMP_5_STAR_RATING', 'H_COMP_6_STAR_RATING', 'H_COMP_7_STAR_RATING', 'H_GLOB_STAR_RATING', 'H_INDI_STAR_RATING', 'H_NUMB_COMP', 'PSI_90_SAFETY_DEN', 'MORT_30_CABG', 'MORT_30_CABG_DEN', 'READM_30_CABG', 'READM_30_CABG_DEN', 'OP_32', 'OP_32_DEN', 'OP_33', 'OP_33_DEN', 'OP_35_ADM', 'OP_35_ADM_DEN', 'OP_35_ED', 'OP_35_ED_DEN', 'OP_36', 'OP_36_DEN']

In [75]:
print(df.columns)

Index(['PROVIDER_ID', 'HAI_1_DEN_VOL', 'HAI_2_DEN_VOL', 'HAI_3_DEN_VOL',
       'HAI_4_DEN_VOL', 'HAI_5_DEN_VOL', 'HAI_6_DEN_VOL', 'HAI_1_DEN_PRED',
       'HAI_2_DEN_PRED', 'HAI_3_DEN_PRED', 'HAI_4_DEN_PRED', 'HAI_5_DEN_PRED',
       'HAI_6_DEN_PRED', 'HAI_1', 'HAI_2', 'HAI_3', 'HAI_4', 'HAI_5', 'HAI_6',
       'READM_30_HOSP_WIDE', 'READM_30_HIP_KNEE', 'EDAC_30_HF',
       'READM_30_COPD', 'EDAC_30_AMI', 'EDAC_30_PN', 'MORT_30_STK',
       'MORT_30_PN', 'MORT_30_HF', 'MORT_30_COPD', 'MORT_30_AMI',
       'COMP_HIP_KNEE', 'READM_30_HOSP_WIDE_DEN', 'READM_30_HIP_KNEE_DEN',
       'EDAC_30_HF_DEN', 'READM_30_COPD_DEN', 'EDAC_30_AMI_DEN',
       'EDAC_30_PN_DEN', 'MORT_30_STK_DEN', 'MORT_30_PN_DEN', 'MORT_30_HF_DEN',
       'MORT_30_COPD_DEN', 'MORT_30_AMI_DEN', 'COMP_HIP_KNEE_DEN', 'OP_2',
       'OP_2_DEN', 'OP_3B', 'OP_3B_DEN', 'OP_8', 'OP_8_DEN', 'OP_10',
       'OP_10_DEN', 'OP_13', 'OP_13_DEN', 'OP_18B', 'OP_18B_DEN', 'OP_22',
       'OP_22_DEN', 'OP_23', 'OP_23_DEN', 'OP_29', 'OP_29_DEN', 'OP_30',
       'OP_30_DEN', 'PSI_4_SURG_COMP', 'PSI_4_SURG_COMP_DEN', 'PSI_90_SAFETY',
       'IMM_3_DEN', 'IMM_3', 'PC_01', 'PC_01_DEN', 'SEP_1', 'SEP_1_DEN',
       'ED_2B', 'ED_2B_DEN', 'H_RESP_RATE_P', 'H_COMP_1_STAR_RATING',
       'H_COMP_2_STAR_RATING', 'H_COMP_3_STAR_RATING', 'H_COMP_5_STAR_RATING',
       'H_COMP_6_STAR_RATING', 'H_COMP_7_STAR_RATING', 'H_GLOB_STAR_RATING',
       'H_INDI_STAR_RATING', 'H_NUMB_COMP', 'PSI_90_SAFETY_DEN',
       'MORT_30_CABG', 'MORT_30_CABG_DEN', 'READM_30_CABG',
       'READM_30_CABG_DEN', 'OP_32', 'OP_32_DEN', 'OP_33', 'OP_33_DEN',
       'OP_35_ADM', 'OP_35_ADM_DEN', 'OP_35_ED', 'OP_35_ED_DEN', 'OP_36',
       'OP_36_DEN'],
      dtype='object')

In [79]:
dUse=df[df.columns.intersection(ixUse)]

In [76]:
print(ixDuse)

Index(['READM_30_HOSP_WIDE', 'READM_30_HIP_KNEE', 'EDAC_30_HF',
       'READM_30_COPD', 'EDAC_30_AMI', 'EDAC_30_PN', 'MORT_30_STK',
       'MORT_30_PN', 'MORT_30_HF', 'MORT_30_COPD', 'MORT_30_AMI',
       'COMP_HIP_KNEE', 'OP_2', 'OP_8', 'OP_10', 'OP_13', 'OP_22', 'OP_23',
       'OP_29', 'OP_30', 'PSI_4_SURG_COMP', 'PSI_90_SAFETY', 'IMM_3', 'PC_01',
       'SEP_1', 'H_COMP_1_STAR_RATING', 'H_COMP_2_STAR_RATING',
       'H_COMP_3_STAR_RATING', 'H_COMP_5_STAR_RATING', 'H_COMP_6_STAR_RATING',
       'H_COMP_7_STAR_RATING', 'H_GLOB_STAR_RATING', 'H_INDI_STAR_RATING',
       'MORT_30_CABG', 'READM_30_CABG', 'OP_32', 'OP_33', 'OP_35_ADM',
       'OP_35_ED', 'OP_36'],
      dtype='object')

In [80]:
dUse.head()

   READM_30_HOSP_WIDE  READM_30_HIP_KNEE  ...  OP_35_ED  OP_36
0               0.156              0.046  ...       7.1    0.8
1               0.159              0.039  ...       6.2    1.1
2               0.152              0.046  ...       NaN    1.1
3               0.161                NaN  ...       NaN    1.0
4               0.148                NaN  ...       NaN    NaN

[5 rows x 40 columns]

In [95]:
print(df['OP_2'].isna().sum())

4446

In [91]:
len(df['OP_2'])

4536